import { strToU8, zipSync } from "fflate";
import type { TrainingPackage } from "../src/package-model";
import { makeDraft, nextDraftRevision, packageForExport } from "./draft";
import type { AuthoringDraft, DraftLineage, ReleaseChecklist } from "./draft";
import type { AuthoringIssue } from "./quality";

const PACKAGE_MARKER = "<!--AUTHORED_PACKAGE_DATA-->";

function download(name: string, data: BlobPart, type: string) {
  const url = URL.createObjectURL(new Blob([data], { type }));
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = name;
  anchor.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

function safeJsonForHtml(value: unknown): string {
  return JSON.stringify(value).replace(/</g, "\\u003c").replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
}

export function learnerHtml(entry: TrainingPackage): string {
  if (!__PLAYER_TEMPLATE__.includes(PACKAGE_MARKER)) {
    throw new Error("The authoring build does not contain a learner-player template.");
  }
  const canonical = packageForExport(entry);
  const payload = `<script type="application/json" id="authored-package-data">${safeJsonForHtml(canonical)}</script>`;
  return __PLAYER_TEMPLATE__.replace(PACKAGE_MARKER, payload);
}

export function exportLearnerHtml(entry: TrainingPackage) {
  const canonical = packageForExport(entry);
  download(`${canonical.manifest.id}.html`, learnerHtml(canonical), "text/html;charset=utf-8");
}

export function exportDraft(entry: TrainingPackage, release: ReleaseChecklist, lineage: DraftLineage): AuthoringDraft {
  const canonical = packageForExport(entry);
  const draft = makeDraft(canonical, release, nextDraftRevision(lineage));
  download(
    `${canonical.manifest.id}-course-draft.json`,
    JSON.stringify(draft, null, 2),
    "application/json;charset=utf-8",
  );
  return draft;
}

function releaseChecklistComplete(release: ReleaseChecklist): boolean {
  return release.subjectMatterChecked &&
    release.learningFlowChecked &&
    release.handlingChecked &&
    release.releaseApproved &&
    Boolean(release.reviewerName.trim()) &&
    Boolean(release.reviewerRole.trim()) &&
    Boolean(release.approverName.trim()) &&
    Boolean(release.approverRole.trim()) &&
    Boolean(release.approvalScope.trim()) &&
    Boolean(release.approvalReference.trim()) &&
    /^\d{4}-\d{2}-\d{2}$/.test(release.approvalDate.trim());
}

async function sha256Hex(value: string): Promise<string> {
  const digest = await globalThis.crypto.subtle.digest("SHA-256", new TextEncoder().encode(value));
  return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}

function releaseRecord(entry: TrainingPackage, release: ReleaseChecklist, packageSha256: string) {
  return {
    recordVersion: 2,
    generatedAt: new Date().toISOString(),
    studioVersion: __STUDIO_VERSION__,
    packageId: entry.manifest.id,
    packageVersion: entry.manifest.version,
    packageStatus: entry.manifest.status,
    packageDigest: { algorithm: "SHA-256", value: packageSha256 },
    checklistComplete: releaseChecklistComplete(release),
    approvals: {
      subjectMatterChecked: release.subjectMatterChecked,
      learningFlowChecked: release.learningFlowChecked,
      audienceAndHandlingChecked: release.handlingChecked,
      releaseApproved: release.releaseApproved,
      reviewer: { name: release.reviewerName.trim(), role: release.reviewerRole.trim() },
      approver: { name: release.approverName.trim(), role: release.approverRole.trim() },
      approvalScope: release.approvalScope.trim(),
      approvalReference: release.approvalReference.trim(),
      approvalDate: release.approvalDate.trim(),
    },
    statement:
      "This record captures declarations made in Course Workshop. A release custodian must still inspect the package and repository diff before publication.",
  };
}

function integrationReadme(entry: TrainingPackage): string {
  const id = entry.manifest.id;
  return `# ${entry.manifest.title} — generated course package

This package was generated by Product Practice Course Workshop ${__STUDIO_VERSION__}.

## Trust boundary

Nothing in this ZIP has modified the learning-system repository. A release custodian must inspect it before installation.

## Contents

- \`course-package.json\` — canonical, versioned TrainingPackage data.
- The canonical data includes the course-owned quality profile used by catalogue QA after installation.
- \`src/courses/${id}/course-package.json\` — the same data at its intended repository path.
- \`src/courses/${id}/index.ts\` — a data-only entry module for the shared player.
- \`src/courses/${id}/releases/${entry.manifest.version}.json\` — the dated approval record retained with this released course version.
- \`hosted/index.html\` — the approved single-course page for an individual URL.
- \`release-record.json\` — human review and approval declarations captured at export.
- \`CATALOGUE-ENTRY.txt\` — the manual catalogue equivalent, retained for transparency.
- \`validation-report.json\` — the automated checks visible at export time.
- \`public/courses/${id}/README.md\` — reserved location for a future external-asset route; Workshop media is embedded in the package.

## Controlled release commands

From the repository root, inspect first. Then choose either or both delivery routes:

\`\`\`bash
npm run course:inspect -- path/to/${id}-course-package.zip
npm run course:install -- path/to/${id}-course-package.zip
npm run course:host -- path/to/${id}-course-package.zip
npm run verify
\`\`\`

- \`course:install\` adds the course to \`src/courses/\` and registers it in the combined catalogue.
- \`course:host\` adds its isolated page under \`public/training/${id}/\`; the next build publishes it at \`training/${id}/\`.
- Both refuse to overwrite an existing course. Updating a released course remains a deliberate developer or release-custodian task.
- Inspect the exact Git diff before committing. The scripts never push to GitHub.

The standalone learner HTML exported beside this package does not need installation or a development toolchain.
`;
}

function entryModule(): string {
  return `import type { TrainingPackage } from "../../package-model";
import courseData from "./course-package.json";

/** Data-only package generated by Product Practice Course Workshop. */
export const authoredCourse = courseData as unknown as TrainingPackage;

export default authoredCourse;
`;
}

function catalogueSnippet(id: string): string {
  const identifier = `course${id
    .split("-")
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("")}`;
  return `Add this import to src/package-catalog.ts:

import ${identifier} from "./courses/${id}";

Then add the imported name once to catalogPackages. Inspect the diff before committing.
`;
}

export async function packageZip(entry: TrainingPackage, issues: AuthoringIssue[], release: ReleaseChecklist): Promise<Uint8Array> {
  const canonical = packageForExport(entry);
  const id = canonical.manifest.id;
  const root = `${id}-course-package`;
  const data = JSON.stringify(canonical, null, 2);
  const packageSha256 = await sha256Hex(data);
  const record = releaseRecord(canonical, release, packageSha256);
  const contentBlocked = issues.some((issue) => issue.severity === "error");
  const releaseReady = !contentBlocked && canonical.manifest.status === "available" && record.checklistComplete;
  const report = JSON.stringify(
    {
      generatedAt: new Date().toISOString(),
      studioVersion: __STUDIO_VERSION__,
      packageId: id,
      packageVersion: canonical.manifest.version,
      packageDigest: { algorithm: "SHA-256", value: packageSha256 },
      contentBlocked,
      releaseReady,
      issues,
      statement:
        "Automated checks cover package structure and selected authoring quality rules. The separate release record captures human declarations; neither record is independent review evidence by itself.",
    },
    null,
    2,
  );
  const files: Record<string, Uint8Array> = {
    [`${root}/README.md`]: strToU8(integrationReadme(canonical)),
    [`${root}/course-package.json`]: strToU8(data),
    [`${root}/src/courses/${id}/course-package.json`]: strToU8(data),
    [`${root}/src/courses/${id}/index.ts`]: strToU8(entryModule()),
    [`${root}/src/courses/${id}/releases/${canonical.manifest.version}.json`]: strToU8(JSON.stringify(record, null, 2)),
    [`${root}/hosted/index.html`]: strToU8(learnerHtml(canonical)),
    [`${root}/release-record.json`]: strToU8(JSON.stringify(record, null, 2)),
    [`${root}/CATALOGUE-ENTRY.txt`]: strToU8(catalogueSnippet(id)),
    [`${root}/validation-report.json`]: strToU8(report),
    [`${root}/public/courses/${id}/README.md`]: strToU8(
      "Course Workshop media is embedded in course-package.json and needs no external files. Reserve this namespace for a future controlled external-asset route; never use another course's asset namespace.\n",
    ),
  };
  return zipSync(files, { level: 6 });
}

export async function exportDeveloperPackage(entry: TrainingPackage, issues: AuthoringIssue[], release: ReleaseChecklist) {
  const canonical = packageForExport(entry);
  download(
    `${canonical.manifest.id}-course-package.zip`,
    await packageZip(canonical, issues, release),
    "application/zip",
  );
}

export async function hostedCourseZip(entry: TrainingPackage, release: ReleaseChecklist): Promise<Uint8Array> {
  const canonical = packageForExport(entry);
  const id = canonical.manifest.id;
  const root = `${id}-hosted-course`;
  const data = JSON.stringify(canonical, null, 2);
  const packageSha256 = await sha256Hex(data);
  const readme = `# ${canonical.manifest.title} — individually hosted course

This folder is the isolated learner course exported by Product Practice Course Workshop ${__STUDIO_VERSION__}.

- Open \`index.html\` locally to test it.
- \`course-package.json\` is the canonical course data. Its SHA-256 digest is recorded in \`release-record.json\` so the approval can be checked against the exact content.
- To host it through the learning-system repository, use the repository package and run \`npm run course:host -- <package.zip>\` instead of copying files manually.
- The page contains the complete course text. Treat the destination as public unless the host is access-controlled.
- \`release-record.json\` records the declarations captured at export; it is not independent review evidence.
`;
  return zipSync({
    [`${root}/index.html`]: strToU8(learnerHtml(canonical)),
    [`${root}/course-package.json`]: strToU8(data),
    [`${root}/README.md`]: strToU8(readme),
    [`${root}/release-record.json`]: strToU8(JSON.stringify(releaseRecord(canonical, release, packageSha256), null, 2)),
  }, { level: 6 });
}

export async function exportHostedCourse(entry: TrainingPackage, release: ReleaseChecklist) {
  const canonical = packageForExport(entry);
  download(
    `${canonical.manifest.id}-hosted-course.zip`,
    await hostedCourseZip(canonical, release),
    "application/zip",
  );
}

export async function readJsonFile(file: File): Promise<unknown> {
  try {
    return JSON.parse(await file.text()) as unknown;
  } catch {
    throw new Error("The selected file is not valid JSON.");
  }
}
